# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         release
version:      0.25
version_from: lib/Release.pm
installdirs:  site
requires:
    ConfigReader::Simple:          0
    Net::FTP:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
