# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         release
version:      1.01
version_from: lib/Module/Release.pm
installdirs:  site
requires:
    CGI:                           0
    Config:                        0
    ConfigReader::Simple:          0
    File::Spec:                    0
    HTTP::Cookies:                 0
    HTTP::Request:                 0
    LWP::UserAgent:                0
    Net::FTP:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.23
